### ISSUE TITLE
[ToDo] Speed buffs at spawn

### ISSUE THREAD

**Issue by cgameing** [TerraTerma/TTCore#40]
Can you guys, have speed 2/3 at spawn? Is that possible, I recon you may have to import multiverse or something. Anyway evan will know.

Thanks

**Comment by mosemister** [comment]
Why would we need to import multiverse to change a players speed? It doesnt touch players speed at all?

Anyway yes its possible.

We would need to do it safely. This means getting the area that is spawn. If a player is in it the spawn then use the old way, set the players speed. If the player is not in spawn but there previous location was in spawn then set there speed back to default (1). This will need to be done on player move event. However the original setting of speed can be done on PlayerRespawnEvent

**Comment by cgameing** [comment]
I think I can do this one myself actually

**Comment by cgameing** [comment]
I completed this in the TTGui plugin
